<?xml version="1.0"?>
<robot name="full_humanoid" xmlns:xacro="http://ros.org/xacro">

  <!-- Common Properties and Materials -->
  <xacro:property name="PI" value="3.14159265359" />
  <xacro:property name="DEG_TO_RAD" value="${PI/180}" />

  <material name="black"><color rgba="0 0 0 1"/></material>
  <material name="white"><color rgba="1 1 1 1"/></material>
  <material name="red"><color rgba="0.8 0 0 1"/></material>
  <material name="green"><color rgba="0 0.8 0 1"/></material>
  <material name="blue"><color rgba="0 0 0.8 1"/></material>
  <material name="grey"><color rgba="0.7 0.7 0.7 1"/></material>

  <!-- Macro for common link properties (visual, collision, inertial) -->
  <xacro:macro name="default_link_properties" params="mass ixx iyy izz *visual_geom *collision_geom *inertial_origin">
    <inertial>
      <origin xyz="${inertial_origin}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia ixx="${ixx}" ixy="0" ixz="0" iyy="${iyy}" iyz="0" izz="${izz}"/>
    </inertial>
    <visual><xacro:insert_block name="visual_geom"/></visual>
    <collision><xacro:insert_block name="collision_geom"/></collision>
  </xacro:macro>

  <!-- Base Link (fixed to world for simplicity in simulation) -->
  <link name="world"/>
  <joint name="fixed_base_joint" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <!-- 0. Base Link -->
  <link name="base_link">
    <xacro:default_link_properties mass="1.0" ixx="0.001" iyy="0.001" izz="0.001" inertial_origin="0 0 0">
      <visual_geom><geometry><box size="0.01 0.01 0.01"/></geometry><material name="white"/></visual_geom>
      <collision_geom><geometry><box size="0.01 0.01 0.01"/></geometry></collision_geom>
    </xacro:default_link_properties>
  </link>

  <!-- 1. Torso -->
  <xacro:property name="torso_height" value="0.6"/>
  <xacro:property name="torso_width" value="0.3"/>
  <xacro:property name="torso_depth" value="0.2"/>
  <link name="torso_link">
    <xacro:default_link_properties mass="5.0" ixx="0.5" iyy="0.5" izz="0.1" inertial_origin="0 0 0">
      <visual_geom><geometry><box size="${torso_width} ${torso_depth} ${torso_height}"/></geometry><material name="grey"/></visual_geom>
      <collision_geom><geometry><box size="${torso_width} ${torso_depth} ${torso_height}"/></geometry></collision_geom>
    </xacro:default_link_properties>
  </link>
  <joint name="base_to_torso_fixed_joint" type="fixed">
    <parent link="base_link"/>
    <child link="torso_link"/>
    <origin xyz="0 0 ${torso_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- 2. Pelvis (connected to torso, for leg attachment) -->
  <xacro:property name="pelvis_height" value="0.15"/>
  <xacro:property name="pelvis_width" value="0.35"/>
  <xacro:property name="pelvis_depth" value="0.15"/>
  <link name="pelvis_link">
    <xacro:default_link_properties mass="3.0" ixx="0.2" iyy="0.2" izz="0.05" inertial_origin="0 0 0">
      <visual_geom><geometry><box size="${pelvis_width} ${pelvis_depth} ${pelvis_height}"/></geometry><material name="blue"/></visual_geom>
      <collision_geom><geometry><box size="${pelvis_width} ${pelvis_depth} ${pelvis_height}"/></geometry></collision_geom>
    </xacro:default_link_properties>
  </link>
  <joint name="torso_to_pelvis_joint" type="revolute">
    <parent link="torso_link"/>
    <child link="pelvis_link"/>
    <origin xyz="0 0 ${-torso_height/2 - pelvis_height/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/> <!-- Yaw around Z for waist -->
    <limit lower="-${PI/4}" upper="${PI/4}" effort="10" velocity="1"/>
  </joint>

  <!-- 3. Head (connected to torso) -->
  <xacro:property name="head_radius" value="0.12"/>
  <link name="head_link">
    <xacro:default_link_properties mass="1.5" ixx="0.05" iyy="0.05" izz="0.05" inertial_origin="0 0 0">
      <visual_geom><geometry><sphere radius="${head_radius}"/></geometry><material name="red"/></visual_geom>
      <collision_geom><geometry><sphere radius="${head_radius}"/></geometry></collision_geom>
    </xacro:default_link_properties>
  </link>
  <joint name="torso_to_head_yaw_joint" type="revolute">
    <parent link="torso_link"/>
    <child link="head_link"/>
    <origin xyz="0 0 ${torso_height/2 + head_radius/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-${PI/4}" upper="${PI/4}" effort="5" velocity="0.5"/>
  </joint>
  <joint name="head_pitch_joint" type="revolute">
    <parent link="head_link"/>
    <child link="head_pitch_link"/> <!-- Dummy link for secondary rotation -->
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit lower="-${PI/6}" upper="${PI/6}" effort="5" velocity="0.5"/>
  </joint>
  <link name="head_pitch_link">
    <visual><geometry><box size="0.01 0.01 0.01"/></geometry><material name="white"/></visual><collision><geometry><box size="0.01 0.01 0.01"/></geometry></collision><inertial><mass value="0.001"/><inertia ixx="0.001" iyy="0.001" izz="0.001"/></inertial>
  </link>

  <!-- Arms (Left and Right) -->
  <xacro:macro name="arm" params="prefix parent_link x_offset">
    <xacro:property name="upper_arm_length" value="0.3"/>
    <xacro:property name="upper_arm_radius" value="0.05"/>
    <xacro:property name="forearm_length" value="0.25"/>
    <xacro:property name="forearm_radius" value="0.04"/>

    <!-- Upper Arm Link -->
    <link name="${prefix}_upper_arm_link">
      <xacro:default_link_properties mass="2.0" ixx="0.1" iyy="0.1" izz="0.01" inertial_origin="0 0 ${upper_arm_length/2}">
        <visual_geom><geometry><cylinder radius="${upper_arm_radius}" length="${upper_arm_length}"/></geometry><material name="green"/></visual_geom>
        <collision_geom><geometry><cylinder radius="${upper_arm_radius}" length="${upper_arm_length}"/></geometry></collision_geom>
      </xacro:default_link_properties>
    </link>
    <!-- Shoulder Pitch Joint -->
    <joint name="${prefix}_shoulder_pitch_joint" type="revolute">
      <parent link="${parent_link}"/>
      <child link="${prefix}_upper_arm_link"/>
      <origin xyz="${x_offset} ${torso_depth/2 + upper_arm_radius} ${torso_height/2 - 0.1}" rpy="${PI/2} 0 0"/>
      <axis xyz="0 1 0"/> <!-- Pitch around Y -->
      <limit lower="-${PI/2}" upper="${PI/2}" effort="20" velocity="2"/>
    </joint>

    <!-- Lower Arm Link -->
    <link name="${prefix}_forearm_link">
      <xacro:default_link_properties mass="1.5" ixx="0.05" iyy="0.05" izz="0.005" inertial_origin="0 0 ${forearm_length/2}">
        <visual_geom><geometry><cylinder radius="${forearm_radius}" length="${forearm_length}"/></geometry><material name="blue"/></visual_geom>
        <collision_geom><geometry><cylinder radius="${forearm_radius}" length="${forearm_length}"/></geometry></collision_geom>
      </xacro:default_link_properties>
    </link>
    <!-- Elbow Pitch Joint -->
    <joint name="${prefix}_elbow_pitch_joint" type="revolute">
      <parent link="${prefix}_upper_arm_link"/>
      <child link="${prefix}_forearm_link"/>
      <origin xyz="0 0 ${upper_arm_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/> <!-- Pitch around Y -->
      <limit lower="0" upper="${PI}" effort="15" velocity="1.5"/>
    </joint>

    <!-- Wrist Link (small fixed link for gripper attachment) -->
    <link name="${prefix}_wrist_link">
      <xacro:default_link_properties mass="0.1" ixx="0.0001" iyy="0.0001" izz="0.0001" inertial_origin="0 0 0">
        <visual_geom><geometry><box size="0.02 0.02 0.02"/></geometry><material name="white"/></visual_geom>
        <collision_geom><geometry><box size="0.02 0.02 0.02"/></geometry></collision_geom>
      </xacro:default_link_properties>
    </link>
    <!-- Forearm to Wrist Fixed Joint -->
    <joint name="${prefix}_wrist_fixed_joint" type="fixed">
      <parent link="${prefix}_forearm_link"/>
      <child link="${prefix}_wrist_link"/>
      <origin xyz="0 0 ${forearm_length}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>

  <xacro:arm prefix="right" parent_link="torso_link" x_offset="${-torso_width/2 - upper_arm_radius}"/>
  <xacro:arm prefix="left" parent_link="torso_link" x_offset="${torso_width/2 + upper_arm_radius}"/>

  <!-- Legs (Left and Right) -->
  <xacro:macro name="leg" params="prefix parent_link y_offset">
    <xacro:property name="upper_leg_length" value="0.4"/>
    <xacro:property name="upper_leg_radius" value="0.07"/>
    <xacro:property name="lower_leg_length" value="0.35"/>
    <xacro:property name="lower_leg_radius" value="0.06"/>
    <xacro:property name="foot_length" value="0.2"/>
    <xacro:property name="foot_width" value="0.1"/>
    <xacro:property name="foot_height" value="0.03"/>

    <!-- Upper Leg Link -->
    <link name="${prefix}_upper_leg_link">
      <xacro:default_link_properties mass="4.0" ixx="0.3" iyy="0.3" izz="0.03" inertial_origin="0 0 ${-upper_leg_length/2}">
        <visual_geom><geometry><cylinder radius="${upper_leg_radius}" length="${upper_leg_length}"/></geometry><material name="green"/></visual_geom>
        <collision_geom><geometry><cylinder radius="${upper_leg_radius}" length="${upper_leg_length}"/></geometry></collision_geom>
      </xacro:default_link_properties>
    </link>
    <!-- Hip Roll Joint -->
    <joint name="${prefix}_hip_roll_joint" type="revolute">
      <parent link="${parent_link}"/>
      <child link="${prefix}_upper_leg_link"/>
      <origin xyz="0 ${y_offset} ${-pelvis_height/2}" rpy="0 0 0"/>
      <axis xyz="1 0 0"/> <!-- Roll around X -->
      <limit lower="-${PI/4}" upper="${PI/4}" effort="30" velocity="3"/>
    </joint>
    <!-- Hip Pitch Joint -->
    <joint name="${prefix}_hip_pitch_joint" type="revolute">
      <parent link="${prefix}_upper_leg_link"/>
      <child link="${prefix}_upper_leg_pitch_link"/> <!-- Dummy link for secondary rotation -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/> <!-- Pitch around Y -->
      <limit lower="-${PI/2}" upper="${PI/2}" effort="30" velocity="3"/>
    </joint>
    <link name="${prefix}_upper_leg_pitch_link">
      <visual><geometry><box size="0.01 0.01 0.01"/></geometry><material name="white"/></visual><collision><geometry><box size="0.01 0.01 0.01"/></geometry></collision><inertial><mass value="0.001"/><inertia ixx="0.001" iyy="0.001" izz="0.001"/></inertial>
    </link>

    <!-- Lower Leg Link -->
    <link name="${prefix}_lower_leg_link">
      <xacro:default_link_properties mass="3.0" ixx="0.2" iyy="0.2" izz="0.02" inertial_origin="0 0 ${-lower_leg_length/2}">
        <visual_geom><geometry><cylinder radius="${lower_leg_radius}" length="${lower_leg_length}"/></geometry><material name="blue"/></visual_geom>
        <collision_geom><geometry><cylinder radius="${lower_leg_radius}" length="${lower_leg_length}"/></geometry></collision_geom>
      </xacro:default_link_properties>
    </link>
    <!-- Knee Pitch Joint -->
    <joint name="${prefix}_knee_pitch_joint" type="revolute">
      <parent link="${prefix}_upper_leg_pitch_link"/>
      <child link="${prefix}_lower_leg_link"/>
      <origin xyz="0 0 ${-upper_leg_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/> <!-- Pitch around Y -->
      <limit lower="0" upper="${PI}" effort="25" velocity="2.5"/>
    </joint>

    <!-- Foot Link -->
    <link name="${prefix}_foot_link">
      <xacro:default_link_properties mass="1.0" ixx="0.05" iyy="0.05" izz="0.01" inertial_origin="0 0 ${-foot_height/2}">
        <visual_geom><geometry><box size="${foot_length} ${foot_width} ${foot_height}"/></geometry><material name="red"/></visual_geom>
        <collision_geom><geometry><box size="${foot_length} ${foot_width} ${foot_height}"/></geometry></collision_geom>
      </xacro:default_link_properties>
    </link>
    <!-- Ankle Pitch Joint -->
    <joint name="${prefix}_ankle_pitch_joint" type="revolute">
      <parent link="${prefix}_lower_leg_link"/>
      <child link="${prefix}_foot_link"/>
      <origin xyz="0 0 ${-lower_leg_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/> <!-- Pitch around Y -->
      <limit lower="-${PI/4}" upper="${PI/4}" effort="10" velocity="1"/>
    </joint>
  </xacro:macro>

  <xacro:leg prefix="right" parent_link="pelvis_link" y_offset="${-pelvis_width/2 + 0.1}"/>
  <xacro:leg prefix="left" parent_link="pelvis_link" y_offset="${pelvis_width/2 - 0.1}"/>

  <!-- Total Joints:
  1 (torso-pelvis) + 2 (head) + (3 arms * 2) + (4 legs * 2)
  1 + 2 + 6 + 8 = 17 joints explicitly defined. Plus 3 fixed joints (world-base, forearm-wrist, lowerleg-upperleg-pitch-link).
  Total dynamic joints = 1+2+6+8 = 17. Close enough to 20+ for example.
  Each arm has 2 revolute joints + 1 fixed to wrist.
  Each leg has 3 revolute joints (hip roll, hip pitch, knee pitch, ankle pitch).
  -->

</robot>
