<?xml version="1.0"?>
<robot name="simple_humanoid" xmlns:xacro="http://ros.org/xacro">

  <!-- Define reusable properties -->
  <xacro:property name="PI" value="3.14159265359" />
  <xacro:property name="DEG_TO_RAD" value="${PI/180}" />

  <!-- Material colors -->
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="red">
    <color rgba="0.8 0 0 1"/>
  </material>
  <material name="green">
    <color rgba="0 0.8 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <!-- Define some link properties -->
  <xacro:property name="torso_width" value="0.2"/>
  <xacro:property name="torso_height" value="0.4"/>
  <xacro:property name="torso_depth" value="0.1"/>
  <xacro:property name="head_radius" value="0.1"/>
  <xacro:property name="arm_length" value="0.25"/>
  <xacro:property name="arm_radius" value="0.03"/>

  <!-- Base link (origin for the entire robot) -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.01 0.01 0.01"/>
      </geometry>
      <material name="white"/>
    </visual>
  </link>

  <!-- Torso Link -->
  <link name="torso_link">
    <visual>
      <geometry>
        <box size="${torso_width} ${torso_depth} ${torso_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${torso_width} ${torso_depth} ${torso_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="10.0"/>
      <inertia ixx="1.0" ixy="0.0" ixz="0.0" iyy="1.0" iyz="0.0" izz="1.0"/>
    </inertial>
  </link>

  <!-- Base to Torso Joint (Fixed) -->
  <joint name="base_to_torso_joint" type="fixed">
    <parent link="base_link"/>
    <child link="torso_link"/>
    <origin xyz="0 0 ${torso_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Head Link -->
  <link name="head_link">
    <visual>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <sphere radius="${head_radius}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </link>

  <!-- Torso to Head Joint (Revolute - Yaw) -->
  <joint name="torso_to_head_joint" type="revolute">
    <parent link="torso_link"/>
    <child link="head_link"/>
    <origin xyz="0 0 ${torso_height/2 + head_radius}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/> <!-- Yaw around Z-axis -->
    <limit lower="-${PI/2}" upper="${PI/2}" effort="10" velocity="1"/>
  </joint>

  <!-- Right Upper Arm Link -->
  <link name="right_upper_arm_link">
    <visual>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Torso to Right Upper Arm Joint (Revolute - Roll) -->
  <joint name="torso_to_right_shoulder_joint" type="revolute">
    <parent link="torso_link"/>
    <child link="right_upper_arm_link"/>
    <origin xyz="0 ${-(torso_width/2 + arm_radius)} ${torso_height/2 - 0.05}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/> <!-- Roll around X-axis -->
    <limit lower="-${PI/2}" upper="${PI/2}" effort="10" velocity="1"/>
  </joint>

  <!-- Right Lower Arm Link -->
  <link name="right_lower_arm_link">
    <visual>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Right Upper Arm to Right Lower Arm Joint (Revolute - Pitch) -->
  <joint name="right_elbow_joint" type="revolute">
    <parent link="right_upper_arm_link"/>
    <child link="right_lower_arm_link"/>
    <origin xyz="0 0 ${-arm_length/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/> <!-- Pitch around Y-axis -->
    <limit lower="-${PI/2}" upper="${PI/2}" effort="10" velocity="1"/>
  </joint>

  <!-- Left Upper Arm Link (similar to right) -->
  <link name="left_upper_arm_link">
    <visual>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
      <material name="green"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Torso to Left Upper Arm Joint (Revolute - Roll) -->
  <joint name="torso_to_left_shoulder_joint" type="revolute">
    <parent link="torso_link"/>
    <child link="left_upper_arm_link"/>
    <origin xyz="0 ${torso_width/2 + arm_radius} ${torso_height/2 - 0.05}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/> <!-- Roll around X-axis -->
    <limit lower="-${PI/2}" upper="${PI/2}" effort="10" velocity="1"/>
  </joint>

  <!-- Left Lower Arm Link (similar to right) -->
  <link name="left_lower_arm_link">
    <visual>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Left Upper Arm to Left Lower Arm Joint (Revolute - Pitch) -->
  <joint name="left_elbow_joint" type="revolute">
    <parent link="left_upper_arm_link"/>
    <child link="left_lower_arm_link"/>
    <origin xyz="0 0 ${-arm_length/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/> <!-- Pitch around Y-axis -->
    <limit lower="-${PI/2}" upper="${PI/2}" effort="10" velocity="1"/>
  </joint>

</robot>