global_costmap:
  global_costmap:
    ros__parameters:
      track_unknown_space: true
      use_sim_time: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_topic: "/map" # Map from VSLAM
        # For this example, we assume a static map is available or VSLAM provides one
        # If VSLAM map is dynamic, ensure map_subscribe_transient_local is true in launch
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: "scan cloud" # LiDAR and Depth Camera
        scan:
          topic: "/lidar_scan" # From Isaac Sim LiDAR
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          data_type: "LaserScan"
          clearing: true
          marking: true
          is_lidar: true
          raytrace_range: 3.0
          obstacle_range: 2.5
        cloud:
          topic: "/stereo_camera/points" # From Isaac Sim depth camera
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          data_type: "PointCloud2"
          clearing: true
          marking: true
          raytrace_range: 3.0
          obstacle_range: 2.5
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0 # Higher value makes robot keep more distance
        inflation_radius: 0.5 # Radius around obstacles to inflate

local_costmap:
  local_costmap:
    ros__parameters:
      track_unknown_space: true
      use_sim_time: true
      plugins: ["obstacle_layer", "inflation_layer"]
      global_frame: odom # Local costmap is relative to odometry frame
      robot_base_frame: base_link
      update_frequency: 5.0 # How often to update the local costmap
      publish_frequency: 2.0 # How often to publish the local costmap
      width: 5.0 # Size of the local costmap in meters
      height: 5.0
      resolution: 0.05 # Resolution of the costmap in meters/cell
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: "scan cloud"
        scan:
          topic: "/lidar_scan"
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          data_type: "LaserScan"
          clearing: true
          marking: true
          is_lidar: true
          raytrace_range: 3.0
          obstacle_range: 2.5
        cloud:
          topic: "/stereo_camera/points"
          max_obstacle_height: 2.0
          min_obstacle_height: 0.0
          data_type: "PointCloud2"
          clearing: true
          marking: true
          raytrace_range: 3.0
          obstacle_range: 2.5
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 3.0
        inflation_radius: 0.5
